// Estados y Municipios de México
// Incluye los 32 estados con sus municipios más importantes

export interface Municipio {
  nombre: string;
}

export interface Estado {
  codigo: string;
  nombre: string;
  municipios: Municipio[];
}

export const estadosMexico: Estado[] = [
  {
    codigo: "AGU",
    nombre: "Aguascalientes",
    municipios: [
      { nombre: "Aguascalientes" },
      { nombre: "Asientos" },
      { nombre: "Calvillo" },
      { nombre: "Cosío" },
      { nombre: "Jesús María" },
      { nombre: "Pabellón de Arteaga" },
      { nombre: "Rincón de Romos" },
      { nombre: "San José de Gracia" },
      { nombre: "Tepezalá" },
      { nombre: "El Llano" },
      { nombre: "San Francisco de los Romo" },
    ],
  },
  {
    codigo: "BC",
    nombre: "Baja California",
    municipios: [
      { nombre: "Ensenada" },
      { nombre: "Mexicali" },
      { nombre: "Tecate" },
      { nombre: "Tijuana" },
      { nombre: "Playas de Rosarito" },
      { nombre: "San Quintín" },
      { nombre: "San Felipe" },
    ],
  },
  {
    codigo: "BCS",
    nombre: "Baja California Sur",
    municipios: [
      { nombre: "Comondú" },
      { nombre: "Mulegé" },
      { nombre: "La Paz" },
      { nombre: "Los Cabos" },
      { nombre: "Loreto" },
    ],
  },
  {
    codigo: "CAM",
    nombre: "Campeche",
    municipios: [
      { nombre: "Calkiní" },
      { nombre: "Campeche" },
      { nombre: "Carmen" },
      { nombre: "Champotón" },
      { nombre: "Hecelchakán" },
      { nombre: "Hopelchén" },
      { nombre: "Palizada" },
      { nombre: "Tenabo" },
      { nombre: "Escárcega" },
      { nombre: "Calakmul" },
      { nombre: "Candelaria" },
    ],
  },
  {
    codigo: "CHIS",
    nombre: "Chiapas",
    municipios: [
      { nombre: "Tuxtla Gutiérrez" },
      { nombre: "San Cristóbal de las Casas" },
      { nombre: "Tapachula" },
      { nombre: "Comitán de Domínguez" },
      { nombre: "Palenque" },
      { nombre: "Ocosingo" },
      { nombre: "Villaflores" },
      { nombre: "Tonalá" },
      { nombre: "Chiapa de Corzo" },
      { nombre: "Cintalapa" },
    ],
  },
  {
    codigo: "CHIH",
    nombre: "Chihuahua",
    municipios: [
      { nombre: "Chihuahua" },
      { nombre: "Juárez" },
      { nombre: "Cuauhtémoc" },
      { nombre: "Delicias" },
      { nombre: "Hidalgo del Parral" },
      { nombre: "Nuevo Casas Grandes" },
      { nombre: "Jiménez" },
      { nombre: "Camargo" },
      { nombre: "Guachochi" },
      { nombre: "Ascensión" },
    ],
  },
  {
    codigo: "CDMX",
    nombre: "Ciudad de México",
    municipios: [
      { nombre: "Álvaro Obregón" },
      { nombre: "Azcapotzalco" },
      { nombre: "Benito Juárez" },
      { nombre: "Coyoacán" },
      { nombre: "Cuajimalpa de Morelos" },
      { nombre: "Cuauhtémoc" },
      { nombre: "Gustavo A. Madero" },
      { nombre: "Iztacalco" },
      { nombre: "Iztapalapa" },
      { nombre: "La Magdalena Contreras" },
      { nombre: "Miguel Hidalgo" },
      { nombre: "Milpa Alta" },
      { nombre: "Tláhuac" },
      { nombre: "Tlalpan" },
      { nombre: "Venustiano Carranza" },
      { nombre: "Xochimilco" },
    ],
  },
  {
    codigo: "COAH",
    nombre: "Coahuila",
    municipios: [
      { nombre: "Saltillo" },
      { nombre: "Torreón" },
      { nombre: "Monclova" },
      { nombre: "Piedras Negras" },
      { nombre: "Acuña" },
      { nombre: "Parras" },
      { nombre: "Sabinas" },
      { nombre: "Múzquiz" },
      { nombre: "San Pedro" },
      { nombre: "Ramos Arizpe" },
    ],
  },
  {
    codigo: "COL",
    nombre: "Colima",
    municipios: [
      { nombre: "Armería" },
      { nombre: "Colima" },
      { nombre: "Comala" },
      { nombre: "Coquimatlán" },
      { nombre: "Cuauhtémoc" },
      { nombre: "Ixtlahuacán" },
      { nombre: "Manzanillo" },
      { nombre: "Minatitlán" },
      { nombre: "Tecomán" },
      { nombre: "Villa de Álvarez" },
    ],
  },
  {
    codigo: "DGO",
    nombre: "Durango",
    municipios: [
      { nombre: "Durango" },
      { nombre: "Gómez Palacio" },
      { nombre: "Lerdo" },
      { nombre: "Santiago Papasquiaro" },
      { nombre: "Guadalupe Victoria" },
      { nombre: "Pueblo Nuevo" },
      { nombre: "El Oro" },
      { nombre: "Vicente Guerrero" },
      { nombre: "Nombre de Dios" },
      { nombre: "Canatlán" },
    ],
  },
  {
    codigo: "GTO",
    nombre: "Guanajuato",
    municipios: [
      { nombre: "León" },
      { nombre: "Irapuato" },
      { nombre: "Celaya" },
      { nombre: "Salamanca" },
      { nombre: "Guanajuato" },
      { nombre: "San Miguel de Allende" },
      { nombre: "Pénjamo" },
      { nombre: "Silao" },
      { nombre: "Dolores Hidalgo" },
      { nombre: "San Francisco del Rincón" },
      { nombre: "Acámbaro" },
      { nombre: "Valle de Santiago" },
    ],
  },
  {
    codigo: "GRO",
    nombre: "Guerrero",
    municipios: [
      { nombre: "Acapulco de Juárez" },
      { nombre: "Chilpancingo de los Bravo" },
      { nombre: "Iguala de la Independencia" },
      { nombre: "Zihuatanejo de Azueta" },
      { nombre: "Taxco de Alarcón" },
      { nombre: "Chilapa de Álvarez" },
      { nombre: "Tlapa de Comonfort" },
      { nombre: "Ayutla de los Libres" },
      { nombre: "Petatlán" },
      { nombre: "Atoyac de Álvarez" },
    ],
  },
  {
    codigo: "HGO",
    nombre: "Hidalgo",
    municipios: [
      { nombre: "Pachuca de Soto" },
      { nombre: "Tulancingo" },
      { nombre: "Tula de Allende" },
      { nombre: "Tepeji del Río" },
      { nombre: "Huejutla de Reyes" },
      { nombre: "Ixmiquilpan" },
      { nombre: "Actopan" },
      { nombre: "Apan" },
      { nombre: "Tizayuca" },
      { nombre: "Mineral de la Reforma" },
    ],
  },
  {
    codigo: "JAL",
    nombre: "Jalisco",
    municipios: [
      { nombre: "Guadalajara" },
      { nombre: "Zapopan" },
      { nombre: "Tlaquepaque" },
      { nombre: "Tonalá" },
      { nombre: "Tlajomulco de Zúñiga" },
      { nombre: "Puerto Vallarta" },
      { nombre: "Lagos de Moreno" },
      { nombre: "Tepatitlán de Morelos" },
      { nombre: "El Salto" },
      { nombre: "Zapotlanejo" },
      { nombre: "Ocotlán" },
      { nombre: "Arandas" },
      { nombre: "Tequila" },
      { nombre: "Chapala" },
    ],
  },
  {
    codigo: "MEX",
    nombre: "Estado de México",
    municipios: [
      { nombre: "Toluca" },
      { nombre: "Ecatepec de Morelos" },
      { nombre: "Naucalpan de Juárez" },
      { nombre: "Nezahualcóyotl" },
      { nombre: "Tlalnepantla de Baz" },
      { nombre: "Chimalhuacán" },
      { nombre: "Atizapán de Zaragoza" },
      { nombre: "Cuautitlán Izcalli" },
      { nombre: "Metepec" },
      { nombre: "Texcoco" },
      { nombre: "Tultitlán" },
      { nombre: "Ixtapaluca" },
      { nombre: "Valle de Chalco Solidaridad" },
      { nombre: "Nicolás Romero" },
    ],
  },
  {
    codigo: "MICH",
    nombre: "Michoacán",
    municipios: [
      { nombre: "Morelia" },
      { nombre: "Uruapan" },
      { nombre: "Zamora" },
      { nombre: "Lázaro Cárdenas" },
      { nombre: "Pátzcuaro" },
      { nombre: "Apatzingán" },
      { nombre: "Zitácuaro" },
      { nombre: "Hidalgo" },
      { nombre: "La Piedad" },
      { nombre: "Sahuayo" },
    ],
  },
  {
    codigo: "MOR",
    nombre: "Morelos",
    municipios: [
      { nombre: "Cuernavaca" },
      { nombre: "Jiutepec" },
      { nombre: "Cuautla" },
      { nombre: "Temixco" },
      { nombre: "Emiliano Zapata" },
      { nombre: "Yautepec" },
      { nombre: "Xochitepec" },
      { nombre: "Puente de Ixtla" },
      { nombre: "Zacatepec" },
      { nombre: "Jojutla" },
    ],
  },
  {
    codigo: "NAY",
    nombre: "Nayarit",
    municipios: [
      { nombre: "Tepic" },
      { nombre: "Bahía de Banderas" },
      { nombre: "Compostela" },
      { nombre: "Ixtlán del Río" },
      { nombre: "Santiago Ixcuintla" },
      { nombre: "Tuxpan" },
      { nombre: "San Blas" },
      { nombre: "Acaponeta" },
      { nombre: "Tecuala" },
      { nombre: "Rosamorada" },
    ],
  },
  {
    codigo: "NL",
    nombre: "Nuevo León",
    municipios: [
      { nombre: "Monterrey" },
      { nombre: "Guadalupe" },
      { nombre: "San Nicolás de los Garza" },
      { nombre: "Apodaca" },
      { nombre: "San Pedro Garza García" },
      { nombre: "General Escobedo" },
      { nombre: "Santa Catarina" },
      { nombre: "García" },
      { nombre: "Cadereyta Jiménez" },
      { nombre: "Juárez" },
      { nombre: "Linares" },
      { nombre: "Montemorelos" },
    ],
  },
  {
    codigo: "OAX",
    nombre: "Oaxaca",
    municipios: [
      { nombre: "Oaxaca de Juárez" },
      { nombre: "Salina Cruz" },
      { nombre: "Juchitán de Zaragoza" },
      { nombre: "Tuxtepec" },
      { nombre: "Santa Cruz Xoxocotlán" },
      { nombre: "Huajuapan de León" },
      { nombre: "Tehuantepec" },
      { nombre: "Puerto Escondido" },
      { nombre: "Santa Lucía del Camino" },
      { nombre: "Tlaxiaco" },
    ],
  },
  {
    codigo: "PUE",
    nombre: "Puebla",
    municipios: [
      { nombre: "Puebla" },
      { nombre: "Tehuacán" },
      { nombre: "San Martín Texmelucan" },
      { nombre: "Atlixco" },
      { nombre: "Cholula" },
      { nombre: "Cuautlancingo" },
      { nombre: "Amozoc" },
      { nombre: "Teziutlán" },
      { nombre: "Zacatlán" },
      { nombre: "Huauchinango" },
    ],
  },
  {
    codigo: "QRO",
    nombre: "Querétaro",
    municipios: [
      { nombre: "Querétaro" },
      { nombre: "San Juan del Río" },
      { nombre: "Corregidora" },
      { nombre: "El Marqués" },
      { nombre: "Tequisquiapan" },
      { nombre: "Cadereyta de Montes" },
      { nombre: "Pedro Escobedo" },
      { nombre: "Ezequiel Montes" },
      { nombre: "Jalpan de Serra" },
      { nombre: "Colón" },
    ],
  },
  {
    codigo: "QR",
    nombre: "Quintana Roo",
    municipios: [
      { nombre: "Cancún" },
      { nombre: "Chetumal" },
      { nombre: "Playa del Carmen" },
      { nombre: "Cozumel" },
      { nombre: "Tulum" },
      { nombre: "Felipe Carrillo Puerto" },
      { nombre: "José María Morelos" },
      { nombre: "Bacalar" },
      { nombre: "Isla Mujeres" },
      { nombre: "Puerto Morelos" },
    ],
  },
  {
    codigo: "SLP",
    nombre: "San Luis Potosí",
    municipios: [
      { nombre: "San Luis Potosí" },
      { nombre: "Soledad de Graciano Sánchez" },
      { nombre: "Ciudad Valles" },
      { nombre: "Matehuala" },
      { nombre: "Rioverde" },
      { nombre: "Tamuín" },
      { nombre: "Ébano" },
      { nombre: "Ciudad Fernández" },
      { nombre: "Cárdenas" },
      { nombre: "Tamazunchale" },
    ],
  },
  {
    codigo: "SIN",
    nombre: "Sinaloa",
    municipios: [
      { nombre: "Culiacán" },
      { nombre: "Mazatlán" },
      { nombre: "Los Mochis" },
      { nombre: "Guasave" },
      { nombre: "Guamúchil" },
      { nombre: "Escuinapa" },
      { nombre: "Navolato" },
      { nombre: "El Fuerte" },
      { nombre: "Mocorito" },
      { nombre: "Concordia" },
    ],
  },
  {
    codigo: "SON",
    nombre: "Sonora",
    municipios: [
      { nombre: "Hermosillo" },
      { nombre: "Cajeme" },
      { nombre: "Nogales" },
      { nombre: "San Luis Río Colorado" },
      { nombre: "Navojoa" },
      { nombre: "Guaymas" },
      { nombre: "Agua Prieta" },
      { nombre: "Caborca" },
      { nombre: "Puerto Peñasco" },
      { nombre: "Empalme" },
    ],
  },
  {
    codigo: "TAB",
    nombre: "Tabasco",
    municipios: [
      { nombre: "Centro" },
      { nombre: "Cárdenas" },
      { nombre: "Comalcalco" },
      { nombre: "Huimanguillo" },
      { nombre: "Macuspana" },
      { nombre: "Paraíso" },
      { nombre: "Cunduacán" },
      { nombre: "Jalpa de Méndez" },
      { nombre: "Teapa" },
      { nombre: "Balancán" },
    ],
  },
  {
    codigo: "TAM",
    nombre: "Tamaulipas",
    municipios: [
      { nombre: "Reynosa" },
      { nombre: "Matamoros" },
      { nombre: "Nuevo Laredo" },
      { nombre: "Tampico" },
      { nombre: "Victoria" },
      { nombre: "Altamira" },
      { nombre: "Ciudad Madero" },
      { nombre: "Río Bravo" },
      { nombre: "Ciudad Mante" },
      { nombre: "Valle Hermoso" },
    ],
  },
  {
    codigo: "TLAX",
    nombre: "Tlaxcala",
    municipios: [
      { nombre: "Tlaxcala" },
      { nombre: "Apizaco" },
      { nombre: "Huamantla" },
      { nombre: "Chiautempan" },
      { nombre: "San Pablo del Monte" },
      { nombre: "Zacatelco" },
      { nombre: "Calpulalpan" },
      { nombre: "Tlaxco" },
      { nombre: "Santa Cruz Tlaxcala" },
      { nombre: "Yauhquemehcan" },
    ],
  },
  {
    codigo: "VER",
    nombre: "Veracruz",
    municipios: [
      { nombre: "Veracruz" },
      { nombre: "Xalapa" },
      { nombre: "Coatzacoalcos" },
      { nombre: "Córdoba" },
      { nombre: "Poza Rica de Hidalgo" },
      { nombre: "Minatitlán" },
      { nombre: "Orizaba" },
      { nombre: "Boca del Río" },
      { nombre: "Tuxpan" },
      { nombre: "Papantla" },
      { nombre: "Martínez de la Torre" },
      { nombre: "San Andrés Tuxtla" },
    ],
  },
  {
    codigo: "YUC",
    nombre: "Yucatán",
    municipios: [
      { nombre: "Mérida" },
      { nombre: "Kanasín" },
      { nombre: "Umán" },
      { nombre: "Tizimín" },
      { nombre: "Valladolid" },
      { nombre: "Progreso" },
      { nombre: "Ticul" },
      { nombre: "Motul" },
      { nombre: "Tekax" },
      { nombre: "Izamal" },
    ],
  },
  {
    codigo: "ZAC",
    nombre: "Zacatecas",
    municipios: [
      { nombre: "Zacatecas" },
      { nombre: "Fresnillo" },
      { nombre: "Guadalupe" },
      { nombre: "Jerez" },
      { nombre: "Río Grande" },
      { nombre: "Sombrerete" },
      { nombre: "Loreto" },
      { nombre: "Pinos" },
      { nombre: "Ojocaliente" },
      { nombre: "Villa de Cos" },
    ],
  },
];

// Helper functions
export function getEstados(): Estado[] {
  return estadosMexico;
}

export function getEstadoByCodigo(codigo: string): Estado | undefined {
  return estadosMexico.find((e) => e.codigo === codigo);
}

export function getMunicipiosByEstado(codigoEstado: string): Municipio[] {
  const estado = getEstadoByCodigo(codigoEstado);
  return estado ? estado.municipios : [];
}
